name: Documentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd doc
      - run: mkdir ouptut
      - uses: docker://pandoc/latex:2.9
        with: 
          args: "howToBuildADuck.md --pdf-engine=xelatex  -V 'mainfont:DejaVu Sans' -V 'geometry: left=2cm,right=2cm,top=3cm,bottom=3cm' -o output/howToBuildADuck.pdf"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output