name: PlatformIO CI examples

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [-c ./examples/BMP180Example/platformio.ini ./examples/BMP180Example/,
                  -c ./examples/BMP280Example/platformio.ini ./examples/BMP280Example/]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        platformio lib -g install file://.

    - name: Run PlatformIO
      run: platformio ci --lib="." ${{ matrix.example }}
